#!/usr/bin/env bash

DEPLOY_HOST="${DEPLOY_HOST:-c6v111379}"
DEPLOY_PORT="${DEPLOY_PORT:-22}"
DEPLOY_USER="${DEPLOY_USER:-root}"
DEPLOY_PATH="${DEPLOY_PATH:-/var/www/portfolio/deploy}"
DEPLOY_BRANCH="${DEPLOY_BRANCH:-dev}"
